add current_user to watchers tasks
ITAR089IF/project-management-tool pull request #50
Opened 2018-11-19 21:43 UTC by boikonataliii

**STATUS**
READY

**DESCRIPTION**
add current user to task's watchers when he create it

**CHECK LIST**
- [ ] specs added
- [ ] specs passed
- [ ] code coverage >90%
- [ ] DB indexes added if needed
- [ ] seed.rb file is updated if needed
- [ ] PR is reviewed manually again (to make sure you have 100% ready code)
- [ ] PR doesn't have conflicts with main branch
- [ ] I've checked new feature as logged in and logged out user if needed
- [ ] "let!" is used in specs

2018-11-21 13:13 UTC, AndriySolonyna requested changes

2018-11-21 13:13 UTC, AndriySolonyna commented on app/controllers/account/tasks_controller.rb
> +    if !@task.assignee.watching?(@task)
unless

2018-11-21 13:13 UTC, AndriySolonyna commented on app/views/account/tasks/assign.js.erb
> +<% if @task.assignee == current_user %>
code assignee == user should be placed in Task model

2018-11-21 13:13 UTC, AndriySolonyna commented on spec/controllers/account/tasks_controller_spec.rb
> +      expect{ post :create, params: { project_id: project.id, task: { title: Faker::Lorem.sentence }}}.to change(TaskWatch, :count).by(1)
user.task_watchs

2018-11-23 19:55 UTC, igorkasyanchuk approved these changes

2018-11-24 13:03 UTC, merged